### ISSUE TITLE
Consider changing CyBioReactor max Storage

### ISSUE THREAD

**Issue by leonard84** [PrimeSonic/PrimeSonicSubnauticaMods#54]
With the current storage progression 2x2, 3x2, 3x3 it is impossible to add two 2x2 units, e.g.  bulbo tree samples. So even a 4x2 layout would be better than 3x3. For backward compatibility it would be better to just add a line either 4x3, or 3x4, since the last upgrade stack doesn't yet have an increased storage this change would fit imho.

https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/blob/master/MoreCyclopsUpgrades/Monobehaviors/CyBioReactorMono.cs#L519

I can create a PR if you want.

**Comment by PrimeSonic** [comment]
Since I am already starting a larger balancing overhaul on a new branch [MoreCyclopsUpgrade 3.1](https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/tree/MCU_3-1), where I intend on working through several balancing issues, I think this is a good enough time to reconsider the storage space of the Cyclops BioReactor.

I understand the argument to be made for allowing two 2x2 items in the container.  
And I can agree that given the cost of the BioBoosters, it's a fair reward to obtain even if it starts to make the Cyclops BioReactor a little too close in size to the original base bioreactor.

With this in mind, I think the best compromise right now would be to have the third BioBooster expand the space to 4x3 while also reducing the max power by 50 units to keep with the same linear progression scale.

Making the storage space larger would automatically be backwards compatible since the custom save data stores nothing about the position of the items in the container, only the order in which they were added.  
And the reduction in power capacity can also be made backwards compatible by simply adding a `Math.Min` check when loading save data.

I appreciate the offer to make a pull request. But since I'm already working on a branch for updates anyways, it will take me little time to make this update myself.

**Comment by PrimeSonic** [comment]
@leonard84 
https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/commit/d2b55276297d92d89540bc5f2a849c20b9d08c7a

This will be released in the 3.1 update, which should also introduce a few more balancing changes as well as options for players who wish to use something more or less restrictive than the recommendations I will provide.

**Comment by leonard84** [comment]
@PrimeSonic thanks for the quick fix, I also think that 4x3 with +150 Power is a good compromise.

I also noticed that when multiple items are added they are consumed in parallel, like in `Better BioReactor`. My question would be, is the power unit/s production the same for one 2x2 compared to four 1x1 units?

When you release 3.1 could you also add Vortex support.

**Comment by PrimeSonic** [comment]
I suppose it's not made clear enough in the description page in **MoreCyclopsUpgrades**.  
But to clarify: **BetterBioReactor** was created _directly_ from what was accomplished with the Cyclops BioReactor. It's basically just taking all the functionality that was created from the ground up for the Cyclops and applies it to the original base Bioreactor.

In short, everything mentioned in the Description page for [BetterBioReactor](https://www.nexusmods.com/subnautica/mods/218) was originally true of the Cyclops BioReactor.  

>The speed at which items decompose is now based on their size. An item that is 2x2 will decompose 4 times faster than an item that is 1x1.
    All this ensures that nothing has to "wait its turn" to be processed in the Bioreactor and that there's no penalty or advantage over using items of different sizes.

As for Vortex support, since I don't use it myself and have no intention to start using it again, I can't make any promises about compatibility or correctness.  
The only thing I can do is enable Vortex on the files. But I can't offer any real support if something goes wrong.

**Comment by leonard84** [comment]
> As for Vortex support, since I don't use it myself and have no intention to start using it again, I can't make any promises about compatibility or correctness.
The only thing I can do is enable Vortex on the files. But I can't offer any real support if something goes wrong.

Fair enough, it should work fine I imported the Mod manually in Vortex and had no problems. Enabling it just reduces the hassle for users that want to use it.

I'll close this issue as it has been addressed already.

**Comment by leonard84** [comment]
Actually a 4x3 layout is inferior to a 6x2 layout, while having the same cell count the latter one allows for the usage of three 2x2 units instead of two 2x2 and four 1x1.

**Comment by PrimeSonic** [comment]
There are bigger changes coming to the Cyclops BioReactor along with the 3.1 update.  
I will go ahead and let 6x2 be the final size for the people out there who insist on using poop in the bioreactors even though it's not all that great.

This issue will be closed as the change will be coming in version 3.1.
