### ISSUE TITLE
Cyclops BioReactor not buildable

### ISSUE THREAD

**Issue by Sod-Almighty** [PrimeSonic/PrimeSonicSubnauticaMods#57]
Thanks for creating these very useful mods.

However, I find that the Cyclops Bioreactor cannot be built and doesn't exist - either in the Habitat Builder menus or the Blueprints list. I have the standard Bioreactor blueprint.

Additionally, I upgraded to the latest version of your Cyclops Upgrades mod, and my extra Upgrades stations disappeared along with their contents :(

**Comment by PrimeSonic** [comment]
Github issues are not the appropriate place to report your personal support requests.

What you are describing is only happening to you, likely due to some conflict or other issue in your specific setup.

You are encouraged to seek out support on the Subnautica Modding Discord. 
https://discord.gg/UpWuWwq

Github Issues should be limited to legitimate bugs or reasonable feature requests.
