### ISSUE TITLE
Upgrading mod to latest version corrupts save file

### ISSUE THREAD

**Issue by Sod-Almighty** [PrimeSonic/PrimeSonicSubnauticaMods#58]
My previous report wasn't good enough for you? How about the fact that I now have a _locker full of buildable objects_ instead of hard-won inventory items, thus destroying my entire savegame? Is that a serious enough bug to warrant creating a github issue?

Also, when someone thanks you for your work, and reports a problem, it is generally expected that you NOT act like an arrogant arsehole. Just FYI.

Perhaps if your mod entry on Nexusmods bothered to mention a discord, I would've gone there instead of searching you out on github. But it doesn't.

**Comment by PrimeSonic** [comment]
> Perhaps if your mod entry on Nexusmods bothered to mention a discord, I would've gone there instead of searching you out on github. But it doesn't.

This pinned message is right at the top of the [posts](https://www.nexusmods.com/subnautica/mods/101?tab=posts)
![image](https://user-images.githubusercontent.com/39146191/55717074-874edd00-59c6-11e9-9dc6-c85e9ad6b90a.png)  
This message is right on my Nexus profile.  
![image](https://user-images.githubusercontent.com/39146191/55717402-46a39380-59c7-11e9-85ab-3c114d303cdb.png)

You may have thanked me, and that's cool, but you were the first one to act arrogant, thinking that the above didn't apply to you. And I will not be emotionally manipulated into making any more exceptions.  
It was exactly due to being constantly hounded by people everyday, more often than not with issues made of their own accord, that almost had be quit the modding scene entirely.  

Again, what you have is not something that will result in me making an updates to the mod because it more like has everything to do with your individual set up and how you've updated things.  
Cause what you're describing sounds like exactly what happens when you mess with the SMLHelper TechTypeCache.  
And the mod page says in big red letter not to touch those files without knowing exactly what you're doing, then it's not my mod's fault that you broke your save.

Sorry, but these issues are not for support.  
And if I don't keep firm on that, I could even up burning out and find myself done with modding altogether.  
I'm sending you to the best resource I know of to get this sorted out: A community full of people who have helped with any number of mod issues. I am only one person. And if I spent all my precious little free time helping everyone individually, I would have no time left to actually make mods anymore.  
https://discord.gg/UpWuWwq
If I sound like an arrogant asshole, it's because you came to me acting like you were more deserving of my individual time than everyone else.  
And when I have so little of it to spend on actually creating mods, I have to spend it wisely.
